/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Medico;
import Model.MedicoDAO;
import javax.swing.JOptionPane;


public class CadMed extends javax.swing.JFrame {
    private static CadMed cadMedUnic;
    private Medico m = new Medico();
    
    
    public CadMed() {
        initComponents();
    }

    public static CadMed getCadMed(){
        if(cadMedUnic == null){
            cadMedUnic = new CadMed();
        }
        return cadMedUnic;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotCadMed = new javax.swing.JLabel();
        rotNome = new javax.swing.JLabel();
        rotIdade = new javax.swing.JLabel();
        rotCpf = new javax.swing.JLabel();
        rotSalario = new javax.swing.JLabel();
        rotEspec = new javax.swing.JLabel();
        rotCrm = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        cxIdade = new javax.swing.JTextField();
        cxCpf = new javax.swing.JTextField();
        cxSalario = new javax.swing.JTextField();
        cxEspec = new javax.swing.JTextField();
        cxCrm = new javax.swing.JTextField();
        btIns = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rotCadMed.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        rotCadMed.setText("CADASTRO DE MEDICO");

        rotNome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rotNome.setText("NOME:");

        rotIdade.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rotIdade.setText("IDADE:");

        rotCpf.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rotCpf.setText("CPF:");

        rotSalario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rotSalario.setText("SALARIO:");

        rotEspec.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rotEspec.setText("ESPECIALIZACAO:");

        rotCrm.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rotCrm.setText("CRM:");

        btIns.setText("INSERIR");
        btIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsActionPerformed(evt);
            }
        });

        btSair.setText("SAIR");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rotCadMed))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rotEspec)
                                .addComponent(rotCrm, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rotSalario, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rotCpf, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rotIdade, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(rotNome)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxNome)
                            .addComponent(cxCpf)
                            .addComponent(cxSalario)
                            .addComponent(cxEspec)
                            .addComponent(cxCrm)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btIns)
                                    .addComponent(cxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 34, Short.MAX_VALUE)))))
                .addGap(20, 20, 20)
                .addComponent(btSair)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rotCadMed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotIdade)
                    .addComponent(cxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotCpf)
                    .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotSalario)
                    .addComponent(cxSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotEspec)
                    .addComponent(cxEspec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotCrm)
                    .addComponent(cxCrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIns)
                    .addComponent(btSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsActionPerformed
        cadMed();
        limpar();
    }//GEN-LAST:event_btInsActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    public void cadMed(){
        try {
        
        String nome = cxNome.getText().trim();
        String idadeStr = cxIdade.getText().trim();
        String cpfStr = cxCpf.getText().trim();
        String salarioStr = cxSalario.getText().trim();
        String espec = cxEspec.getText().trim();
        String crmStr = cxCrm.getText().trim();

        
        if (nome.isEmpty() || idadeStr.isEmpty() || cpfStr.isEmpty() || crmStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome, Idade, CPF e CRM são obrigatórios!", "Campos Vazios", JOptionPane.WARNING_MESSAGE);
            return; 
        }

       
        Medico novoMedico = new Medico();
        novoMedico.setNome(nome);
        novoMedico.setIdade(Integer.parseInt(idadeStr));
        novoMedico.setCpf(Integer.parseInt(cpfStr));
        novoMedico.setSalario(Float.parseFloat(salarioStr));
        novoMedico.setEspec(espec);
        novoMedico.setCrm(Integer.parseInt(crmStr));

        
        MedicoDAO medicoDAO = new MedicoDAO();
        medicoDAO.save(novoMedico);

       
        JOptionPane.showMessageDialog(
            this,
            "Médico(a) " + novoMedico.getNome() + " cadastrado(a) com sucesso!",
            "CADASTRO DE MÉDICO",
            JOptionPane.INFORMATION_MESSAGE
        );
        
        limpar(); 

    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(
            this,
            "Os campos IDADE, CPF, SALÁRIO e CRM devem ser números válidos!",
            "ERRO DE ENTRADA",
            JOptionPane.ERROR_MESSAGE
        );
    } catch (Exception e) {
        
        JOptionPane.showMessageDialog(
            this,
            "Ocorreu um erro ao salvar o médico:\n" + e.getMessage(),
            "ERRO DE BANCO DE DADOS",
            JOptionPane.ERROR_MESSAGE
        );
        e.printStackTrace(); 
    }

    }
    
    public void limpar(){
        cxNome.setText("");
        cxIdade.setText("");
        cxCpf.setText("");
        cxCrm.setText("");
        cxSalario.setText("");
        cxEspec.setText("");
        
    }
    
    public void sair(){
		int resp = JOptionPane.showConfirmDialog(
					null,
					"Deseja realmente sair?",
					"Saida",
					JOptionPane.YES_NO_OPTION
				);
			if(resp == 0){
				System.exit(0);	
			}
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadMed().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIns;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxCpf;
    private javax.swing.JTextField cxCrm;
    private javax.swing.JTextField cxEspec;
    private javax.swing.JTextField cxIdade;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxSalario;
    private javax.swing.JLabel rotCadMed;
    private javax.swing.JLabel rotCpf;
    private javax.swing.JLabel rotCrm;
    private javax.swing.JLabel rotEspec;
    private javax.swing.JLabel rotIdade;
    private javax.swing.JLabel rotNome;
    private javax.swing.JLabel rotSalario;
    // End of variables declaration//GEN-END:variables
}
