
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import View.ImpEst;
import View.CadEst;
import Model.Estagiario;
import Model.EstagiarioDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

public class IntEstagiario extends javax.swing.JFrame {
    private static IntEstagiario intEstUnic;

  
    public IntEstagiario() {
        initComponents();
    }

    public static IntEstagiario getIntEstagiario(){

        if(intEstUnic == null){
            intEstUnic = new IntEstagiario();
        }
        return intEstUnic;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotMenuEst = new javax.swing.JLabel();
        rotCpf = new javax.swing.JLabel();
        cxCpf = new javax.swing.JTextField();
        btConsEst = new javax.swing.JButton();
        btAltEst = new javax.swing.JButton();
        btDelEst = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btImpEst = new javax.swing.JButton();
        btnCadEst = new javax.swing.JButton();
        bmEst = new javax.swing.JMenuBar();
        mnEst = new javax.swing.JMenu();
        mnItCadEst = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rotMenuEst.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        rotMenuEst.setText("MENU ESTAGIARIO");

        rotCpf.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        rotCpf.setText("CPF:");

        btConsEst.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btConsEst.setText("CONSULTA ESTAGIARIO");
        btConsEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsEstActionPerformed(evt);
            }
        });

        btAltEst.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btAltEst.setText("ALTERA PERIODO");
        btAltEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltEstActionPerformed(evt);
            }
        });

        btDelEst.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btDelEst.setText("DELETA ESTAGIARIO");
        btDelEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelEstActionPerformed(evt);
            }
        });

        btSair.setText("SAIR");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btImpEst.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btImpEst.setText("APRESENTA ESTAGIARIOS");
        btImpEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImpEstActionPerformed(evt);
            }
        });

        btnCadEst.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnCadEst.setText("Cadastrar Estagiario");
        btnCadEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadEstActionPerformed(evt);
            }
        });

        mnEst.setText("Estagiario");

        mnItCadEst.setText("CADASTRA ESTAGIARIO");
        mnItCadEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItCadEstActionPerformed(evt);
            }
        });
        mnEst.add(mnItCadEst);

        bmEst.add(mnEst);

        setJMenuBar(bmEst);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btDelEst, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btImpEst))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btConsEst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAltEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rotCpf)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cxCpf, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnCadEst)))
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(btSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(rotMenuEst)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(rotMenuEst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rotCpf)
                    .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadEst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsEst)
                    .addComponent(btAltEst))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDelEst)
                    .addComponent(btImpEst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConsEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsEstActionPerformed
        consEst();
        limpar();
    }//GEN-LAST:event_btConsEstActionPerformed

    private void btAltEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltEstActionPerformed
        altEst();
        limpar();
    }//GEN-LAST:event_btAltEstActionPerformed

    private void btDelEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelEstActionPerformed
        delEst();
        limpar();
    }//GEN-LAST:event_btDelEstActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void mnItCadEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItCadEstActionPerformed
        JOptionPane.showMessageDialog(this, "A tela de cadastro de estagiário deve ser criada e chamada aqui.");
    
    }//GEN-LAST:event_mnItCadEstActionPerformed

    private void btImpEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImpEstActionPerformed
        
        ImpEst telaDeListagem = ImpEst.getImpEst(); 
        telaDeListagem.setVisible(true);
        telaDeListagem.listarTab(); 
    }//GEN-LAST:event_btImpEstActionPerformed

    private void btnCadEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadEstActionPerformed
        CadEst.getCadEst().setVisible(true);
    }//GEN-LAST:event_btnCadEstActionPerformed

    
    
    public void delEst() {
        try {
            int cpf = Integer.parseInt(cxCpf.getText().trim());
            int resposta = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja deletar o estagiário com CPF " + cpf + "?", "Confirmação", JOptionPane.YES_NO_OPTION);
            
            if (resposta == JOptionPane.YES_OPTION) {
                EstagiarioDAO estagiarioDAO = new EstagiarioDAO();
                boolean sucesso = estagiarioDAO.deleteByCpf(cpf);
                if (sucesso) {
                    JOptionPane.showMessageDialog(this, "Estagiário deletado com sucesso.");
                } else {
                    JOptionPane.showMessageDialog(this, "Estagiário com CPF " + cpf + " não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O CPF deve ser um número válido.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao deletar estagiário: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void consEst(){
        try {
            int cpf = Integer.parseInt(cxCpf.getText().trim());
            EstagiarioDAO estagiarioDAO = new EstagiarioDAO();
            Estagiario est = estagiarioDAO.findByCpf(cpf);

            if (est != null) {
                String dados = String.format(
                    "DADOS DO ESTAGIÁRIO:\n---------------------------\n" +
                    " - Nome: %s\n - CPF: %d\n - Idade: %d\n" +
                    " - Instituição: %s\n - Período: %d",
                    est.getNome(), est.getCpf(), est.getIdade(),
                    est.getInstituicaoEnsino(), est.getPeriodo()
                );
                JOptionPane.showMessageDialog(this, dados, "Consulta de Estagiário", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Estagiário com CPF " + cpf + " não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O CPF deve ser um número válido.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao consultar estagiário: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
        
    
    
    public void altEst() {
        try {
            int cpf = Integer.parseInt(cxCpf.getText().trim());
            String novoPeriodoStr = JOptionPane.showInputDialog(this, "Digite o novo período para o estagiário com CPF " + cpf + ":");
            
            if (novoPeriodoStr != null && !novoPeriodoStr.trim().isEmpty()) {
                int novoPeriodo = Integer.parseInt(novoPeriodoStr);
                EstagiarioDAO estagiarioDAO = new EstagiarioDAO();
                boolean sucesso = estagiarioDAO.updatePeriodo(cpf, novoPeriodo);
                if (sucesso) {
                    JOptionPane.showMessageDialog(this, "Período atualizado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Estagiário com CPF " + cpf + " não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "CPF e Período devem ser números.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao alterar período: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

            
    public void limpar(){
        cxCpf.setText("");
        cxCpf.requestFocus();
    }
    
    
    public void sair(){
		int resp = JOptionPane.showConfirmDialog(
					null,
					"Deseja realmente sair?",
					"Saida",
					JOptionPane.YES_NO_OPTION
				);
			if(resp == 0){
				this.dispose();	
			}
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntEstagiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntEstagiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntEstagiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntEstagiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntEstagiario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar bmEst;
    private javax.swing.JButton btAltEst;
    private javax.swing.JButton btConsEst;
    private javax.swing.JButton btDelEst;
    private javax.swing.JButton btImpEst;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btnCadEst;
    private javax.swing.JTextField cxCpf;
    private javax.swing.JMenu mnEst;
    private javax.swing.JMenuItem mnItCadEst;
    private javax.swing.JLabel rotCpf;
    private javax.swing.JLabel rotMenuEst;
    // End of variables declaration//GEN-END:variables
}
