

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.IntPaciente;
import View.IntMedico;
import View.IntEstagiario;
import javax.swing.JOptionPane;


public class PrincipalP extends javax.swing.JFrame {


    public PrincipalP() {
        initComponents();
        adicionarAcoesAosMenus();
    }
    private void adicionarAcoesAosMenus() {
    
    menuPa.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            
            IntPaciente.getIntPaciente().setVisible(true);
        }
    });

    menuMe.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            
            IntMedico.getIntMedico().setVisible(true);
        }
    });

    menuEst.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            // Abre a tela de gerenciamento de estagiários
            IntEstagiario.getIntEstagiario().setVisible(true);
        }
    });

    menuSair.addMenuListener(new javax.swing.event.MenuListener() {
        public void menuSelected(javax.swing.event.MenuEvent evt) {

            int resposta = javax.swing.JOptionPane.showConfirmDialog(null, "Deseja realmente sair da aplicação?", "Sair", javax.swing.JOptionPane.YES_NO_OPTION);
            if (resposta == javax.swing.JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        }
 
        public void menuDeselected(javax.swing.event.MenuEvent evt) {}
        public void menuCanceled(javax.swing.event.MenuEvent evt) {}
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotMenu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPri = new javax.swing.JMenu();
        menuPa = new javax.swing.JMenuItem();
        menuMe = new javax.swing.JMenuItem();
        menuEst = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rotMenu.setFont(new java.awt.Font("Serif", 3, 48)); // NOI18N
        rotMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rotMenu.setText("HospitAll");

        menuPri.setText("Menu");

        menuPa.setText("Paciente");
        menuPa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPaActionPerformed(evt);
            }
        });
        menuPri.add(menuPa);

        menuMe.setText("Medico");
        menuPri.add(menuMe);

        menuEst.setText("Estagiario");
        menuPri.add(menuEst);

        jMenuBar1.add(menuPri);

        menuSair.setText("Sair");
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(rotMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(rotMenu)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPaActionPerformed

        public void sair(){
		int resp = JOptionPane.showConfirmDialog(
					null,
					"Deseja realmente sair?",
					"Saida",
					JOptionPane.YES_NO_OPTION
				);
			if(resp == 0){
				System.exit(0);	
			}
	}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuEst;
    private javax.swing.JMenuItem menuMe;
    private javax.swing.JMenuItem menuPa;
    private javax.swing.JMenu menuPri;
    private javax.swing.JMenu menuSair;
    private javax.swing.JLabel rotMenu;
    // End of variables declaration//GEN-END:variables
}
