
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetop;

import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class CadEst extends javax.swing.JFrame {
    private static CadEst cadEstUnic;
    private Estagiario e = new Estagiario();
    /**
     * Creates new form CadEst
     */
    public CadEst() {
        initComponents();
    }

    public static CadEst getCadEst(){
        if(cadEstUnic == null){
            cadEstUnic = new CadEst();
        }
        return cadEstUnic;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotCadEst = new javax.swing.JLabel();
        rotNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        rotIdade = new javax.swing.JLabel();
        cxIdade = new javax.swing.JTextField();
        rotCPf = new javax.swing.JLabel();
        cxCpf = new javax.swing.JTextField();
        rotFacul = new javax.swing.JLabel();
        rotPeriodo = new javax.swing.JLabel();
        rotCurso = new javax.swing.JLabel();
        cxFacul = new javax.swing.JTextField();
        cxPeriodo = new javax.swing.JTextField();
        cxCurso = new javax.swing.JTextField();
        btIns = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rotCadEst.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        rotCadEst.setText("CADASTRO DE ESTAGIARIO");

        rotNome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rotNome.setText("NOME:");

        rotIdade.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rotIdade.setText("IDADE:");

        rotCPf.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rotCPf.setText("CPF:");

        rotFacul.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rotFacul.setText("FACULDADE:");

        rotPeriodo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rotPeriodo.setText("PERIODO:");

        rotCurso.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rotCurso.setText("CURSO:");

        btIns.setText("INSERIR");
        btIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsActionPerformed(evt);
            }
        });

        btSair.setText("SAIR");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotCPf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rotIdade, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rotFacul, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rotPeriodo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rotCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rotNome, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btIns)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(btSair))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cxCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                        .addComponent(cxFacul)
                                        .addComponent(cxCurso)
                                        .addComponent(cxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(rotCadEst))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rotCadEst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotIdade)
                    .addComponent(cxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotCPf)
                    .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotFacul)
                    .addComponent(cxFacul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotPeriodo)
                    .addComponent(cxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotCurso)
                    .addComponent(cxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIns)
                    .addComponent(btSair))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsActionPerformed
        try{
            cadEst();
        } catch (PerEstException pee){
            pee.impPerEstException();
        }
        limpar();
    }//GEN-LAST:event_btInsActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

public void cadEst() throws PerEstException { // Mantemos o throws, pois o botão já trata
    try {
        // --- 1. Coleta e Validação dos Dados ---
        String nome = cxNome.getText().trim();
        String idadeStr = cxIdade.getText().trim();
        String cpfStr = cxCpf.getText().trim();
        String instituicao = cxFacul.getText().trim(); // Pega o texto do campo 'cxFacul'
        String periodoStr = cxPeriodo.getText().trim();
        String curso = cxCurso.getText().trim();

        // Validação de campos vazios
        if (nome.isEmpty() || idadeStr.isEmpty() || cpfStr.isEmpty() || instituicao.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome, Idade, CPF e Faculdade são obrigatórios!", "Campos Vazios", JOptionPane.WARNING_MESSAGE);
            return; 
        }

        // --- 2. Criação do Objeto Estagiario ---
        Estagiario novoEstagiario = new Estagiario();
        
        // Populando o objeto com os dados da tela
        novoEstagiario.setNome(nome);
        novoEstagiario.setIdade(Integer.parseInt(idadeStr));
        novoEstagiario.setCpf(Integer.parseInt(cpfStr));
        
        // Usando os métodos corretos da classe Estagiario que definimos
        novoEstagiario.setInstituicaoEnsino(instituicao); 
        novoEstagiario.setPeriodo(Integer.parseInt(periodoStr)); // Pode lançar PerEstException
        novoEstagiario.setCurso(curso);
        
        // --- 3. Chamada ao DAO para Salvar no Banco ---
        EstagiarioDAO estagiarioDAO = new EstagiarioDAO();
        estagiarioDAO.save(novoEstagiario);

        // --- 4. Feedback de Sucesso ---
        JOptionPane.showMessageDialog(
            this,
            "Estagiário(a) " + novoEstagiario.getNome() + " cadastrado(a) com sucesso!",
            "CADASTRO DE ESTAGIÁRIO",
            JOptionPane.INFORMATION_MESSAGE
        );
        
        limpar(); // Limpa os campos para o próximo cadastro

    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(
            this,
            "Os campos IDADE, CPF e PERÍODO devem ser números válidos!",
            "ERRO DE ENTRADA",
            JOptionPane.ERROR_MESSAGE
        );
    } catch (PerEstException pee) {
        // Re-lançamos a exceção para que o método do botão a capture, como no seu código original
        throw pee; 
    } catch (Exception e) {
        // Captura outros erros (ex: CPF duplicado, falha de conexão)
        JOptionPane.showMessageDialog(
            this,
            "Ocorreu um erro ao salvar o estagiário:\n" + e.getMessage(),
            "ERRO DE BANCO DE DADOS",
            JOptionPane.ERROR_MESSAGE
        );
        e.printStackTrace();
    }
}
    
    public void limpar(){
        cxNome.setText("");
        cxIdade.setText("");
        cxCpf.setText("");
        cxPeriodo.setText("");
        cxFacul.setText("");
        cxCurso.setText("");
    }
    
    public void sair(){
		int resp = JOptionPane.showConfirmDialog(
					null,
					"Deseja realmente sair?",
					"Saida",
					JOptionPane.YES_NO_OPTION
				);
			if(resp == 0){
				System.exit(0);	
			}
    }    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadEst().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIns;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxCpf;
    private javax.swing.JTextField cxCurso;
    private javax.swing.JTextField cxFacul;
    private javax.swing.JTextField cxIdade;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxPeriodo;
    private javax.swing.JLabel rotCPf;
    private javax.swing.JLabel rotCadEst;
    private javax.swing.JLabel rotCurso;
    private javax.swing.JLabel rotFacul;
    private javax.swing.JLabel rotIdade;
    private javax.swing.JLabel rotNome;
    private javax.swing.JLabel rotPeriodo;
    // End of variables declaration//GEN-END:variables
}
